version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000" # HOST:CONTAINER
    volumes:
      - ./app:/app # OURAPP:CONTAINER
    command: > # to go to next line
      sh -c "python manage.py runserver 0.0.0.0:8000"
